# This file was generated by GoReleaser. DO NOT EDIT.
class Awschain < Formula
  desc "awschain is set current AWS* environment variables to envchain namespace."
  homepage "https://github.com/tatsuo48/awschain"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tatsuo48/awschain/releases/download/v0.1.2/awschain_darwin_x86_64.tar.gz"
    sha256 "f22eb5f69e4fcd921e35472427b60d6bae6aa0c9a53a168e87306e992ad06bfe"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tatsuo48/awschain/releases/download/v0.1.2/awschain_linux_x86_64.tar.gz"
      sha256 "d66d6453839ad6f53f687e4efda78be0be2386f03902a6e7ab80ea49d52ddd7e"
    end
  end

  def install
    bin.install "awschain"
  end

  test do
    system "#{bin}/awschain", "-h"
  end
end
