# This file was generated by GoReleaser. DO NOT EDIT.
class Awschain < Formula
  desc "awschain is set current AWS* environment variables to envchain namespace."
  homepage "https://github.com/tatsuo48/awschain"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tatsuo48/awschain/releases/download/v0.1.1/awschain_darwin_x86_64.tar.gz"
    sha256 "62c258f91167ae48bc1523b8a3219b5f250e3824ccdb963f88f199f2e13ec209"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tatsuo48/awschain/releases/download/v0.1.1/awschain_linux_x86_64.tar.gz"
      sha256 "6070ffcb17fbc4c01740a848ba5d6087af15517be4fc227728b3b00ef27dad5a"
    end
  end

  def install
    bin.install "awschain"
  end

  test do
    system "#{bin}/awschain", "-h"
  end
end
