# This file was generated by GoReleaser. DO NOT EDIT.
class Awschain < Formula
  desc "awschain is set current AWS* environment variables to envchain namespace."
  homepage "https://github.com/tatsuo48/awschain"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tatsuo48/awschain/releases/download/v0.1.4/awschain_darwin_x86_64.tar.gz"
    sha256 "d2fe69b2ac1f9470bbf2f06f0094f2b8f70e5f90417e67e05da79b55263713b8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tatsuo48/awschain/releases/download/v0.1.4/awschain_linux_x86_64.tar.gz"
      sha256 "e1d52f58883c702acdd8a5bf25f5a259f75ece331e63a836d76a431d1e943dba"
    end
  end

  def install
    bin.install "awschain"
  end

  test do
    system "#{bin}/awschain", "-v"
  end
end
