# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsource < Formula
  desc "ECS Task Definition tool to display resources such as CPU, memory, and memory reservations in an easy-to-read format."
  homepage "https://github.com/tatsuo48/ecsource"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tatsuo48/ecsource/releases/download/v1.0.1/ecsource_darwin_x86_64.tar.gz"
      sha256 "c89fbe3599e0f1b7bb7f1d251e0997b6007e890364a4fc3b73e6b447feffc6d0"

      def install
        bin.install "ecsource"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tatsuo48/ecsource/releases/download/v1.0.1/ecsource_darwin_arm64.tar.gz"
      sha256 "07a0f11deb0996d858aabb3361c541bf40f03c960af0039f933f7d34a3c115e0"

      def install
        bin.install "ecsource"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tatsuo48/ecsource/releases/download/v1.0.1/ecsource_linux_x86_64.tar.gz"
      sha256 "bb39c9ea8f639daf1bb46751b2ff43e8378f1e11876bf2c83d6e1b8b31db7441"

      def install
        bin.install "ecsource"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tatsuo48/ecsource/releases/download/v1.0.1/ecsource_linux_arm64.tar.gz"
      sha256 "59db923f50a5f3f9a1015843f7016f0263eef49ca1ba0db1a94d675210de4804"

      def install
        bin.install "ecsource"
      end
    end
  end

  test do
    system "#{bin}/ecsource", "-v"
  end
end
